// <auto-generated />
using CelebrityGuessingGame.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CelebrityGuessingGame.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20240812051142_UpdateSchema2")]
    partial class UpdateSchema2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("CelebrityGuessingGame.Models.Celebrity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetWorth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Celebrities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 58,
                            Birthday = "1962-07-03",
                            Gender = "Male",
                            Height = 1.7,
                            IsAlive = true,
                            Name = "Tom Cruise",
                            Nationality = "American",
                            NetWorth = 570000000m,
                            Occupation = "[\"Actor\"]"
                        },
                        new
                        {
                            Id = 2,
                            Age = 39,
                            Birthday = "1981-09-04",
                            Gender = "Female",
                            Height = 1.6899999999999999,
                            IsAlive = true,
                            Name = "Beyoncé",
                            Nationality = "American",
                            NetWorth = 400000000m,
                            Occupation = "[\"Singer\",\"Actress\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
